import Head from 'next/head'
import Image from 'next/image'
import SideBars from '../components/SideBars'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WhatApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.png"/>
      </Head>
      <SideBars/>
    </div>
  )
}
